### ISSUE TITLE
Mod not marked as client-sided for forge?

### ISSUE THREAD

**Issue by Kjell003** [shiroroku/LootBeams#1]
- Minor issue -

As soon as I install this mod client-sided my server that does not have this mod will say it is incompatible (the red X sign in multiplayer server list).

Can you mark the mod client-side only? Since it only adds visuals client-sided.
Would appreciated it if you could implement this!

**Comment by shiroroku** [comment]
this is just a visual thing with forge. you should still able to connect and use the mod just fine. will fix in a few.

**Comment by shiroroku** [comment]
https://github.com/shiroroku/LootBeams/commit/c4a2d4699e0834744c6a9dc6c92b6a8bfce1d2f2
