### ISSUE TITLE
Loot Beam colours no longer working as of latest update

### ISSUE THREAD

**Issue by NJL5390** [shiroroku/LootBeams#2]
Loot Beams Version: 1.16.5-release-aug1821
Forge Version: 36.2.2
Minecraft Version: 1.16.5

Hello,

I've noticed that after the latest update to this mod that loot beam colours no longer seem to be working in relation to colours of the item names. This issue still occurs without any other mods installed and even with a freshly generated config file. This issue only started happening in the latest update to Loot Beams and does not happen on previous versions.

Latest Version of Loot Beams (1.16.5-release-aug1821):
![2021-08-20_21 00 06](https://user-images.githubusercontent.com/64381954/130288167-b78818d8-9eb2-41e9-92da-8cac7e2643e0.png)

Previous Version (1.16.5-release-aug1121):
![2021-08-20_21 02 38](https://user-images.githubusercontent.com/64381954/130288278-9c031e45-d356-4c62-84f7-634da68d597b.png)

I just want to end by saying that this a neat little mod and one that I never knew I needed! So thank you for making it!

**Comment by shiroroku** [comment]
https://github.com/shiroroku/LootBeams/commit/fae63ca2d9ae85fb52f3c52898c3c9661dad01d5
ty, update will be up soon
