### ISSUE TITLE
Crashes the server and client (version june0123)

### ISSUE THREAD

**Issue by noncom** [shiroroku/LootBeams#21]
The new version crashes the server. Looks like it tries to ask for the client stuff.

Server crash report:
[crash-2023-06-03_22.32.23-server.txt](https://github.com/shiroroku/LootBeams/files/11643923/crash-2023-06-03_22.32.23-server.txt)

But yes, it kind of looks like it could be just a client mod and could work without having it on the server, but if I remove it from the server, that's the crash I'm getting on the client:

[crash-2023-06-03_21.42.44-client.txt](https://github.com/shiroroku/LootBeams/files/11644116/crash-2023-06-03_21.42.44-client.txt)

The previous version iirc also required being present on both the client and the server, but did not crash.
I'm temporarily switching to the old one.

**Comment by Secretname2009** [comment]
I can confirm this issue also happends on the june323 update. The mod for some reason registers an object that has to be present both Client and Server side. Crash logs from both sides are below.
[crash-2023-06-04_13.31.34-client.txt](https://github.com/shiroroku/LootBeams/files/11645490/crash-2023-06-04_13.31.34-client.txt)
[crash-2023-06-04_13.22.35-server.txt](https://github.com/shiroroku/LootBeams/files/11645491/crash-2023-06-04_13.22.35-server.txt)

**Comment by amoooooo** [comment]
oh i didnt know this update was released yet. yeah it wasnt fully ready, havent figured out how to do client only sound registry yet.

**Comment by amoooooo** [comment]
@shiroroku would you be able to pull the latest jars off of cf? its not done
