### ISSUE TITLE
1.12.2 Support of LootBeams with help from Grend_G with Sync Function

### ISSUE THREAD

**Issue by TitooTVGeilo** [shiroroku/LootBeams#24]
Hi,
on the 15.06.2023 have Grend_G her mod ItemBorders a backport to the 1.12.2 version make out and it work nice. 
I hope you can with a help of Grend_G your mod backport now for the 1.12.2 Version of Minecraft. And Why I will so much
the Function of your nice mod and the ItemBorders mod in one Modpack play in the 1.12.2 Area and only your mod miss. 
I hope you can Grend_G say this and with her help your LootBeams mod Backport for 1.12.2. 
And the other think is I hope you or Grend_G can a Sync Function add for the other mod to copy and paste the colors of the 
hex colour system.

MFG
Mirko

**Comment by amoooooo** [comment]
Not backporting to 1.12.2. Ever.
