### ISSUE TITLE
1.19.2 Wall hax when item on floor

### ISSUE THREAD

**Issue by VanilaBOI** [shiroroku/LootBeams#28]
When I drop an item like an enchanted book I see all mobs through walls.

![2023-06-23_13 19 15](https://github.com/shiroroku/LootBeams/assets/86358160/5352f26f-8b39-4ae5-a666-74fe8592cf14)
![2023-06-23_13 19 18](https://github.com/shiroroku/LootBeams/assets/86358160/597e7cc2-874b-4d99-8b24-7245b9c65d49)

**Comment by VanilaBOI** [comment]
Maybe it's because of my Optifine?

**Comment by amoooooo** [comment]
Yes is it. Optifine is bad, don't use it. Use Rubidium + Oculus instead.
