### ISSUE TITLE
[1.20.1] Obscuria Tooltips fucks with the new tooltip item render

### ISSUE THREAD

**Issue by BugmanBugman** [shiroroku/LootBeams#34]
![2023-09-17_00 35 15](https://github.com/shiroroku/LootBeams/assets/40730042/4671841b-21db-4ee8-9027-89c43a78c1b5)

**Comment by BugmanBugman** [comment]
https://www.curseforge.com/minecraft/mc-mods/obscure-tooltips

**Comment by amoooooo** [comment]
Use the legendary tooltips preset, or enable the "Combine rarity" config
option. These mods work together fine, just mess with configs.

**Comment by amoooooo** [comment]
Use the legendary tooltips preset, or enable the "Combine rarity" config option. These mods work together fine, just mess with configs.
