### ISSUE TITLE
[1.19.2]crash when joining world

### ISSUE THREAD

**Issue by Karashok-Leo** [shiroroku/LootBeams#36]
It gets fine after removing lootbeams
[crash-2023-09-17_12.31.55-server.txt](https://github.com/shiroroku/LootBeams/files/12659568/crash-2023-09-17_12.31.55-server.txt)

**Comment by amoooooo** [comment]
this is an issue with Passive Skill Tree as it doesn't expect there to be no player when collecting tooltip data. Report to Daripher (Passive Skill Tree author)
