### ISSUE TITLE
AppleSkin issue

### ISSUE THREAD

**Issue by Sketano** [shiroroku/LootBeams#38]
The area where the nutrition is suppose to be shown is just blank, Unless T is pressed, for some reason?... see pictures below

Without chat open:
<img width="141" alt="image" src="https://github.com/shiroroku/LootBeams/assets/124691491/04f68ea3-3ecf-4761-a3f0-b8d594f5ea8e">

With chat open:
<img width="171" alt="image" src="https://github.com/shiroroku/LootBeams/assets/124691491/0b4a8048-a25c-43a2-a943-d5c8059c5d3d">

**Comment by amoooooo** [comment]
This needs fixed on AppleSkin's end, they dont account for their tooltips being edited.
