### ISSUE TITLE
No presets for 1.18.2?

### ISSUE THREAD

**Issue by YassaaaTU** [shiroroku/LootBeams#39]
Are these presets only for 1.20? 
https://github.com/shiroroku/LootBeams/tree/1.20.1/Presets

**Comment by amoooooo** [comment]
Yes, that's why theyre in the 1.20.1 branch. 1.18.2 is a dead version and
no longer receives support for loot beams. 1.19.2 will only receive major
bug fixes. My main target is always latest.

**Comment by YassaaaTU** [comment]
I see thank you
