### ISSUE TITLE
[1.20.1] Crash, possibly due to apotheosis items

### ISSUE THREAD

**Issue by BugmanBugman** [shiroroku/LootBeams#41]
https://gist.github.com/BugmanBugman/1899cb5d99ade0b3dcddc3de652c1775

**Comment by DaddySpin** [comment]
It seams Loot Beams is outdated.
https://github.com/Shadows-of-Fire/Apotheosis/issues/1083

**Comment by amoooooo** [comment]
![image](https://github.com/shiroroku/LootBeams/assets/6483477/9a5ea7b2-3fec-4414-a88b-888e0070d7dc)
