### ISSUE TITLE
Nametags above items is not smoothly interpolated when being moved positionally

### ISSUE THREAD

**Issue by Kaleidio** [shiroroku/LootBeams#8]
the nametag itself seems to move its position at a much lower framerate, which gives the effect of stuttering when the rest of the game is not.  is the mathematics of movement only firing per server tick rather than render frame?  I have a feeling you are grabbing player position data using a server side method rather than the client side but I'm unsure if this is the case.

**Comment by amoooooo** [comment]
Considering this mod ONLY runs on client side code - no. The math you're describing is not including partial ticks (the time between ticks), but this has never existed in this mod, so i have no idea.

**Comment by Colin-J-Wood** [comment]
Yeah I recently discovered this is the fault of Item Physics, so I'm gonna close this issue when I get back on my alt
