### ISSUE TITLE
[1.16.5][Feature request]Ability to temporarily turn off the beams

### ISSUE THREAD

**Issue by DoctorSigma** [shiroroku/LootBeams#9]
I propose to add the following function: when the key is pressed, the beams turn off and everything becomes like in vanilla, and when pressed again, they turn on again. OR make it so that they are not shown if the player is standing on objects in the radius of the block, for example, and even more so when the player is standing over the object, looks down at the object and cannot pick it up, because the inventory is full.

Why this should be added: Well, for me, the biggest problem is that in my collection there is a mod, and not one, for magnets, that is, it attracts objects to the player under his feet. Accordingly, if the inventory is full, then the object lies under the feet and "follows the player". So, if you look directly, there are no problems, the rays are not visible, but as soon as I look down, for example, to break the iron ore under my feet, I can't see anything because of the light of the rays. I would not like to reduce the height of the beam.
So I suggest either adding a key that turns the beams on/off, OR when the object is close to the player (the distance can be adjusted in chests), then turn off the beams.

**Comment by shiroroku** [comment]
ty for the suggestion, i added a fade out for beams that're too close to the player
https://github.com/shiroroku/LootBeams/commit/d71f439ddb6bb8c2626916c64399363787d3cbbe
